/*
Package table contains functions that use the
github.com/Azure/azure-sdk-for-go/sdk/tables/aztable package
(see: https://github.com/Azure/azure-sdk-for-go/tree/track2-tables ).
While in preview, this must be installed via:

	go get github.com/Azure/azure-sdk-for-go/sdk/internal@track2-tables
	go get github.com/Azure/azure-sdk-for-go/sdk/tables/aztable@track2-tables

In our sample app, we call these via commands in cmd/table.go. These include:

	Available Commands:
	delete       ...
	get          ...
	insert       ...
	insert-kv    ...
	insert-stdin ...
	query        ...
	query-delete ...
	table-create ...
	table-delete ...
	table-list   ...
	upsert-kv    ...

In many cases these functions accept JSON, or print JSON to the standard output,
which causes them to be optimized for the simple CLI use-case.

They are purposely designed to be simple, and able to be borrowed from and
tweaked for more complex use-cases.

The main convention we have is the use of TableClientFromEnv to create a
TableClient from the AZGO_TABLE_ACCOUNT and AZGO_TABLE_KEY environment variables,
and optionally the AZGO_TABLE_TYPE variable which can be set to "storage" to
connect to a Storage Account rather than Cosmos DB (default).
*/
package table
